# SETUP
# 1. Enable Google Cloud Run API
# 2. Enable Google Artifact Registry API
# 3. Create a service account with the following roles:
#   - Cloud Run Admin
#   - Artifact Registry Administrator
#   - Cloud Run Service Agent
#   - Service Account User
# 4. Setup a GitHub secret called GOOGLE_CREDENTIALS with the service account key
# 5. Create a Google Artifact Registry repository
# 6. Setup environment variables in the workflow file


name: Deploy production to Cloud Run

on:
  workflow_dispatch:

env:
    PROJECT_ID: ai-symbol-walk
    GAR_LOCATION: asia-northeast1
    REPOSITORY: dashboard
    SERVICE: dashboard
    REGION: asia-northeast1
    
jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    environment:
      name: production
      url: https://admin.symbolwalk.com

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: 'actions/checkout@v3'

      # https://github.com/google-github-actions/auth
      - name: 'Authenticate to Google Cloud'
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: 'Docker Login' 
        uses: 'docker/login-action@v2'
        with:
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      - name: Create .env file
        run: |
          echo NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ env.PROJECT_ID }} >> .env
          echo NEXT_PUBLIC_FIREBASE_DATABASE_URL=${{ secrets.NEXT_PUBLIC_FIREBASE_DATABASE_URL }} >> .env
          echo FIREBASE_CLIENT_EMAIL=${{ secrets.FIREBASE_CLIENT_EMAIL }} >> .env
          echo FIREBASE_PRIVATE_KEY='"${{ secrets.FIREBASE_PRIVATE_KEY }}"' >> .env
          echo COOKIE_SECRET_PREVIOUS=${{ secrets.COOKIE_SECRET_PREVIOUS }} >> .env
          echo COOKIE_SECRET_CURRENT=${{ secrets.COOKIE_SECRET_CURRENT }} >> .env
          echo NEXT_PUBLIC_ENV=production >> .env
          

      - name: Build and push Docker image
      # https://github.com/docker/build-push-action
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:latest


      # https://github.com/google-github-actions/setup-gcloud
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy dashboard \
            --image ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:latest \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated
